// <auto-generated />
using System;
using Explore_Egypt.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Explore_Egypt.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240415184344_AddedImages20Landmarks")]
    partial class AddedImages20Landmarks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Explore_Egypt.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", "security");
                });

            modelBuilder.Entity("Explore_Egypt.Models.Favour", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("LandmarkID")
                        .HasColumnType("int");

                    b.HasKey("UserId", "LandmarkID");

                    b.HasIndex("LandmarkID");

                    b.ToTable("Favours");
                });

            modelBuilder.Entity("Explore_Egypt.Models.Landmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("CloseTime")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EgyptianStudentTicketPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EgyptianTicketPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ForeignStudentTicketPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ForeignTicketPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("OpenTime")
                        .IsRequired()
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Landmarks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloseTime = new TimeOnly(15, 0, 0),
                            Description = "Abdeen Palace is a historic palace in Cairo, Egypt. Built in the late 19th century, it served as the main residence for Egypt's royal family until 1952. The palace features a blend of Turkish, Moorish, and European architectural styles. Today, it is a museum showcasing opulent interiors, royal artifacts, and beautifully landscaped gardens. Abdeen Palace is a popular tourist attraction, offering a glimpse into Egypt's rich history and royal heritage.",
                            EgyptianStudentTicketPrice = 10.0m,
                            EgyptianTicketPrice = 20.0m,
                            ForeignStudentTicketPrice = 50.0m,
                            ForeignTicketPrice = 100.0m,
                            Latitude = 30.041980595759298,
                            Longitude = 31.2467661930229,
                            Name = "Abdeen Palace",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CloseTime = new TimeOnly(9, 0, 0),
                            Description = "Abu Simbel is an archaeological site in southern Egypt known for its rock-cut temples. The main attraction is the Great Temple of Ramses II, featuring colossal statues and intricate wall carvings. The smaller Temple of Hathor is dedicated to the goddess of love. The site was relocated in the 1960s to save it from flooding. Today, Abu Simbel is a UNESCO World Heritage site and a popular tourist destination",
                            EgyptianStudentTicketPrice = 10.0m,
                            EgyptianTicketPrice = 30.0m,
                            ForeignStudentTicketPrice = 300.0m,
                            ForeignTicketPrice = 600.0m,
                            Latitude = 29.9810966592981,
                            Longitude = 31.143216715340699,
                            Name = "Abu Simbel",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CloseTime = new TimeOnly(16, 30, 0),
                            Description = "The Alexandria National Museum is a prominent museum located in Alexandria, Egypt. It was established in 2003 and is housed in a renovated Italian-style palace dating back to the early 20th century. The museum showcases a diverse collection of artifacts, spanning various historical periods and civilizations, including ancient Egyptian, Greek, Roman, and Islamic artifacts. Visitors can explore exhibits that highlight Alexandria's rich cultural heritage, including sculptures, jewelry, coins, and mummies. The museum also provides insight into the city's history, including its role as a center of trade and scholarship in the ancient world.",
                            EgyptianStudentTicketPrice = 5.0m,
                            EgyptianTicketPrice = 20.0m,
                            ForeignStudentTicketPrice = 90.0m,
                            ForeignTicketPrice = 180.0m,
                            Latitude = 31.200814890268202,
                            Longitude = 29.913219162632899,
                            Name = "Alexandria National Museum",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CloseTime = new TimeOnly(17, 0, 0),
                            Description = "Amir Taz Palace, also known as Beit El-Sennari, is a historic palace located in the heart of Cairo, Egypt. It was constructed during the 19th century under the reign of Khedive Ismail Pasha. The palace exhibits an exquisite blend of Ottoman and Islamic architectural styles, featuring intricate carvings, beautiful stained glass windows, and ornate decorations. Today, the palace serves as a cultural center and a venue for various art exhibitions, concerts, and cultural events. It stands as a testament to Egypt's rich architectural heritage and offers visitors a glimpse into the opulent lifestyle of the past.",
                            EgyptianStudentTicketPrice = 0.0m,
                            EgyptianTicketPrice = 0.0m,
                            ForeignStudentTicketPrice = 0.0m,
                            ForeignTicketPrice = 0.0m,
                            Latitude = 30.0323587576957,
                            Longitude = 31.253664308366901,
                            Name = "Amir Taz Palace",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CloseTime = new TimeOnly(9, 0, 0),
                            Description = "Amr ibn al-As was a prominent Arab military commander and companion of Prophet Muhammad. He played a crucial role in the early Muslim conquests, including the conquest of Egypt in 641 CE. He founded the city of Fustat, which later became Cairo's capital. Amr ibn al-As introduced Islam to the region and governed Egypt for several years. His military and administrative achievements left a lasting impact on the expansion of Islam and the Arab world.",
                            EgyptianStudentTicketPrice = 0.0m,
                            EgyptianTicketPrice = 0.0m,
                            ForeignStudentTicketPrice = 0.0m,
                            ForeignTicketPrice = 0.0m,
                            Latitude = 30.010058193229,
                            Longitude = 31.2331094374956,
                            Name = "Amr Ibn Al-As",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CloseTime = new TimeOnly(19, 0, 0),
                            Description = "Nestled in Aswan, Upper Egypt, the Nubian Museum stands as a testament to the rich history and captivating culture of Nubia. Built in response to the international campaign to save Nubian monuments from rising waters due to the Aswan Dam, the museum opened its doors in 1997",
                            EgyptianStudentTicketPrice = 10.0m,
                            EgyptianTicketPrice = 30.0m,
                            ForeignStudentTicketPrice = 150.0m,
                            ForeignTicketPrice = 300.0m,
                            Latitude = 24.085093977757701,
                            Longitude = 32.887073921252401,
                            Name = "Aswan Museum",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CloseTime = new TimeOnly(9, 0, 0),
                            Description = "Bab al-Futuh is one of the ancient gates of the historic city of Cairo, Egypt. It was constructed during the 11th century and is known for its impressive architectural design. The gate is adorned with intricate carvings and decorative motifs. It served as a main entrance to the old city and is an important cultural and historical landmark. Visitors can admire the gate's grandeur and learn about Cairo's rich history and heritage.",
                            EgyptianStudentTicketPrice = 0.0m,
                            EgyptianTicketPrice = 0.0m,
                            ForeignStudentTicketPrice = 0.0m,
                            ForeignTicketPrice = 0.0m,
                            Latitude = 30.055467889869401,
                            Longitude = 31.263364602674301,
                            Name = "Bab al-Futuh",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            CloseTime = new TimeOnly(9, 0, 0),
                            Description = "Bab Zuweila is a historic gate located in the Old City of Cairo, Egypt. It was built in the 11th century and is one of the few remaining gates from the original city walls. The gate is renowned for its architectural beauty, featuring intricate carvings and decorative elements. It served as a significant entrance to the city and a defensive structure. Today, visitors can explore Bab Zuweila and enjoy panoramic views of Cairo from its elevated platforms.\r\n\r\n\r\n\r\n\r\n",
                            EgyptianStudentTicketPrice = 10.0m,
                            EgyptianTicketPrice = 20.0m,
                            ForeignStudentTicketPrice = 50.0m,
                            ForeignTicketPrice = 100.0m,
                            Latitude = 30.042721232524102,
                            Longitude = 31.257780701819801,
                            Name = "Bab Zuweila",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            CloseTime = new TimeOnly(16, 30, 0),
                            Description = "Baron Empain Palace, also known as the Heliopolis Palace, is a historic landmark located in Heliopolis, Cairo, Egypt. Built in the early 20th century by Belgian industrialist Baron Édouard Empain, it showcases a unique blend of architectural styles, including Hindu and Khmer influences. The palace's distinctive features include its pink hue and intricate detailing. It is considered a masterpiece of architecture and a symbol of Heliopolis. Today, the palace is open to visitors, offering a glimpse into its opulent interiors and the history of its construction.\r\n\r\n\r\n\r\n\r\n",
                            EgyptianStudentTicketPrice = 30.0m,
                            EgyptianTicketPrice = 60.0m,
                            ForeignStudentTicketPrice = 90.0m,
                            ForeignTicketPrice = 180.0m,
                            Latitude = 30.086699776612701,
                            Longitude = 31.330311897686499,
                            Name = "Baron Empain Palace",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            CloseTime = new TimeOnly(0, 0, 0),
                            Description = "The Cairo Tower is a prominent landmark and observation tower located in Cairo, Egypt. Standing at a height of 187 meters (614 feet), it offers panoramic views of the city's skyline and the Nile River. The tower was constructed in the 1960s and features a futuristic design inspired by lotus flowers and ancient Egyptian architecture. It is a popular tourist attraction and a symbol of modern Cairo. The tower also houses a revolving restaurant, offering a unique dining experience with stunning views.\r\n\r\n\r\n\r\n\r\n",
                            EgyptianStudentTicketPrice = 70.0m,
                            EgyptianTicketPrice = 70.0m,
                            ForeignStudentTicketPrice = 250.0m,
                            ForeignTicketPrice = 250.0m,
                            Latitude = 30.0459258601981,
                            Longitude = 31.224288606195099,
                            Name = "Cairo Tower",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            CloseTime = new TimeOnly(17, 0, 0),
                            Description = "Egypt is home to several significant museums showcasing its civilization. The Egyptian Museum in Cairo displays a vast collection of ancient artifacts, including Tutankhamun's treasures. The Luxor Museum highlights artifacts from the ancient city of Thebes. The Nubian Museum in Aswan focuses on Nubian culture and history. The Alexandria National Museum exhibits diverse artifacts from different historical periods. These museums offer invaluable insights into Egypt's rich civilization and heritage.",
                            EgyptianStudentTicketPrice = 40.0m,
                            EgyptianTicketPrice = 80.0m,
                            ForeignStudentTicketPrice = 250.0m,
                            ForeignTicketPrice = 500.0m,
                            Latitude = 30.008417609418,
                            Longitude = 31.248249387380302,
                            Name = "National Museum of Egyptian Civilization",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            CloseTime = new TimeOnly(17, 0, 0),
                            Description = "The Colossi of Memnon are two massive stone statues located on the west bank of the Nile River in Luxor, Egypt. Dating back to the 14th century BCE, they depict Pharaoh Amenhotep III seated on his throne. Standing at around 18 meters (60 feet) tall, they are impressive examples of ancient Egyptian art and craftsmanship. The statues are known for producing a musical sound at sunrise due to natural phenomena, which was believed to be the voice of the mythical Memnon. Today, the Colossi of Memnon attract visitors as iconic remnants of ancient Egypt's grandeur.",
                            EgyptianStudentTicketPrice = 0.0m,
                            EgyptianTicketPrice = 0.0m,
                            ForeignStudentTicketPrice = 0.0m,
                            ForeignTicketPrice = 0.0m,
                            Latitude = 25.720594393258999,
                            Longitude = 32.610531971223701,
                            Name = "Colossi of Memnon",
                            OpenTime = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            CloseTime = new TimeOnly(17, 0, 0),
                            Description = "The Coptic Museum is a renowned museum located in Cairo, Egypt. It is dedicated to preserving and showcasing the rich heritage of Egypt's Coptic Christian community. The museum houses a vast collection of artifacts, including religious manuscripts, icons, textiles, and ancient Coptic artwork. Visitors can explore the museum's exhibits, which provide insights into Coptic history, culture, and art. The museum is an important cultural and historical destination, offering a unique perspective on Egypt's diverse religious and artistic traditions.",
                            EgyptianStudentTicketPrice = 10.0m,
                            EgyptianTicketPrice = 20.0m,
                            ForeignStudentTicketPrice = 120.0m,
                            ForeignTicketPrice = 230.0m,
                            Latitude = 30.005778097385001,
                            Longitude = 31.230398849392401,
                            Name = "Coptic Museum",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            CloseTime = new TimeOnly(17, 0, 0),
                            Description = "Deir el-Medina is an ancient Egyptian village located on the west bank of the Nile near Luxor. It was inhabited by the skilled artisans and workers who constructed royal tombs in the nearby Valley of the Kings. The village is known for its well-preserved structures, including houses, workshops, and a temple dedicated to the goddess Hathor. It offers valuable insights into the daily life, religious practices, and artistic skills of the ancient Egyptians. Deir el-Medina is a significant archaeological site that sheds light on the intricacies of ancient Egyptian society.",
                            EgyptianStudentTicketPrice = 0.0m,
                            EgyptianTicketPrice = 0.0m,
                            ForeignStudentTicketPrice = 0.0m,
                            ForeignTicketPrice = 0.0m,
                            Latitude = 25.7289015527221,
                            Longitude = 32.602222602306902,
                            Name = "Deir el-Medina",
                            OpenTime = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            CloseTime = new TimeOnly(17, 0, 0),
                            Description = "Denderah, located in Upper Egypt, is an ancient Egyptian temple complex dedicated to the goddess Hathor. The centerpiece is the Temple of Hathor, known for its well-preserved and elaborate reliefs and carvings. The temple features a striking hypostyle hall, a sacred lake, and a birthing house. Denderah is renowned for its astronomical ceiling depicting the zodiac signs. It is a significant archaeological site and a testament to the architectural and artistic achievements of ancient Egypt.",
                            EgyptianStudentTicketPrice = 10.0m,
                            EgyptianTicketPrice = 20.0m,
                            ForeignStudentTicketPrice = 120.0m,
                            ForeignTicketPrice = 240.0m,
                            Latitude = 26.1676120463747,
                            Longitude = 32.656609106246201,
                            Name = "Denderah",
                            OpenTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            CloseTime = new TimeOnly(18, 0, 0),
                            Description = "Edfu Temple is an ancient Egyptian temple located on the west bank of the Nile in Edfu, Egypt. It is dedicated to the falcon-headed god Horus and is one of the best-preserved temples in Egypt. The temple was built during the Ptolemaic period and showcases remarkable architecture, including a towering entrance pylon and a well-preserved hypostyle hall. Its walls are adorned with intricate reliefs depicting mythological scenes and rituals. Edfu Temple is a significant religious site and a testament to the grandeur of ancient Egyptian temple construction.",
                            EgyptianStudentTicketPrice = 20.0m,
                            EgyptianTicketPrice = 40.0m,
                            ForeignStudentTicketPrice = 230.0m,
                            ForeignTicketPrice = 450.0m,
                            Latitude = 24.977948234046298,
                            Longitude = 32.873369294153498,
                            Name = "Edfu Temple",
                            OpenTime = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            CloseTime = new TimeOnly(17, 0, 0),
                            Description = "The Egyptian Museum, located in Cairo, Egypt, is one of the world's most significant museums dedicated to ancient Egyptian artifacts. It houses an extensive collection of over 120,000 artifacts, including the treasures of Tutankhamun. The museum showcases statues, mummies, jewelry, and other artifacts spanning several dynasties. Visitors can explore the museum's exhibits, which provide insights into ancient Egyptian history, culture, and art. The Egyptian Museum is a must-visit destination for anyone interested in experiencing the magnificence of Egypt's ancient civilization.",
                            EgyptianStudentTicketPrice = 10.0m,
                            EgyptianTicketPrice = 30.0m,
                            ForeignStudentTicketPrice = 230.0m,
                            ForeignTicketPrice = 450.0m,
                            Latitude = 30.048323478375501,
                            Longitude = 31.233662840341701,
                            Name = "Egyptian Museum",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            CloseTime = new TimeOnly(9, 0, 0),
                            Description = "Al-Azhar Mosque is a historic mosque located in Cairo, Egypt, and is one of the oldest Islamic universities in the world. It was founded in the 10th century and is renowned for its religious and educational significance. The mosque showcases exquisite Islamic architecture, including a beautiful courtyard and minarets. It serves as a center for Islamic learning and hosts religious lectures and conferences. Al-Azhar Mosque is a significant religious and cultural landmark, attracting visitors from around the world.\r\n\r\n\r\n\r\n\r\n",
                            EgyptianStudentTicketPrice = 0.0m,
                            EgyptianTicketPrice = 0.0m,
                            ForeignStudentTicketPrice = 0.0m,
                            ForeignTicketPrice = 0.0m,
                            Latitude = 30.045704450605999,
                            Longitude = 31.2626775702408,
                            Name = "Al-Azhar Mosque",
                            OpenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            CloseTime = new TimeOnly(18, 0, 0),
                            Description = "The Temple of Gerf Hussein is an ancient Egyptian temple located in Upper Nubia, near the Sudanese border. It was relocated during the construction of the Aswan High Dam. The temple was dedicated to the Nubian deity Dedun and was built during the reign of Ramses II. It features well-preserved reliefs depicting Ramses II and various religious scenes. The Temple of Gerf Hussein offers a glimpse into the ancient Egyptian presence in Nubia and the cultural exchange between the two regions.\r\n\r\n\r\n\r\n\r\n",
                            EgyptianStudentTicketPrice = 0.0m,
                            EgyptianTicketPrice = 0.0m,
                            ForeignStudentTicketPrice = 0.0m,
                            ForeignTicketPrice = 0.0m,
                            Latitude = 23.960170000000002,
                            Longitude = 32.867649999999998,
                            Name = "Temple of Gerf Hussein",
                            OpenTime = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            CloseTime = new TimeOnly(9, 0, 0),
                            Description = "The El-Hussein Mosque is a historic mosque located in Cairo, Egypt. It is named after Hussein ibn Ali, the grandson of Prophet Muhammad. The mosque is considered a sacred site and holds religious significance for the Shia Muslim community. It features a beautiful courtyard, minarets, and a dome. The mosque is known for its intricate architectural details and is a popular destination for worshippers and visitors seeking spiritual solace. The El-Hussein Mosque stands as a symbol of religious devotion and cultural heritage in Cairo.\r\n\r\n\r\n\r\n\r\n",
                            EgyptianStudentTicketPrice = 0.0m,
                            EgyptianTicketPrice = 0.0m,
                            ForeignStudentTicketPrice = 0.0m,
                            ForeignTicketPrice = 0.0m,
                            Latitude = 25.744685288303302,
                            Longitude = 32.7515048302213,
                            Name = "Al-Hussein Mosque",
                            OpenTime = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("Explore_Egypt.Models.LandmarkImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LandmarkId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LandmarkId");

                    b.ToTable("LandmarkImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LandmarkId = 1,
                            Url = "\\landmarkImages\\Abdeen_Palace\\1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            LandmarkId = 1,
                            Url = "\\landmarkImages\\Abdeen_Palace\\2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            LandmarkId = 2,
                            Url = "\\landmarkImages\\Abu_Simbel\\1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            LandmarkId = 2,
                            Url = "\\landmarkImages\\Abu_Simbel\\2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            LandmarkId = 3,
                            Url = "\\landmarkImages\\Alexandria_National_Museum\\1.jpg"
                        },
                        new
                        {
                            Id = 6,
                            LandmarkId = 3,
                            Url = "\\landmarkImages\\Alexandria_National_Museum\\2.jpg"
                        },
                        new
                        {
                            Id = 7,
                            LandmarkId = 4,
                            Url = "\\landmarkImages\\Amir_Taz_Palace\\1.jpg"
                        },
                        new
                        {
                            Id = 8,
                            LandmarkId = 4,
                            Url = "\\landmarkImages\\Amir_Taz_Palace\\2.jpg"
                        },
                        new
                        {
                            Id = 9,
                            LandmarkId = 5,
                            Url = "\\landmarkImages\\Amr_Ibn_Al-As\\1.jpg"
                        },
                        new
                        {
                            Id = 10,
                            LandmarkId = 5,
                            Url = "\\landmarkImages\\Amr_Ibn_Al-As\\2.jpg"
                        },
                        new
                        {
                            Id = 11,
                            LandmarkId = 6,
                            Url = "\\landmarkImages\\Aswan_Museum\\1.jpeg"
                        },
                        new
                        {
                            Id = 12,
                            LandmarkId = 6,
                            Url = "\\landmarkImages\\Aswan_Museum\\2.jpeg"
                        },
                        new
                        {
                            Id = 13,
                            LandmarkId = 7,
                            Url = "\\landmarkImages\\Bab-al-Futuh\\1.jpg"
                        },
                        new
                        {
                            Id = 14,
                            LandmarkId = 7,
                            Url = "\\landmarkImages\\Bab-al-Futuh\\2.jpeg"
                        },
                        new
                        {
                            Id = 15,
                            LandmarkId = 8,
                            Url = "\\landmarkImages\\Bab-Zuweila\\1.jpg"
                        },
                        new
                        {
                            Id = 16,
                            LandmarkId = 8,
                            Url = "\\landmarkImages\\Bab-Zuweila\\2.jpg"
                        },
                        new
                        {
                            Id = 17,
                            LandmarkId = 9,
                            Url = "\\landmarkImages\\Baron_Empain_Palace\\1.jpg"
                        },
                        new
                        {
                            Id = 18,
                            LandmarkId = 10,
                            Url = "\\landmarkImages\\Cairo_Tower\\1.jpg"
                        },
                        new
                        {
                            Id = 19,
                            LandmarkId = 10,
                            Url = "\\landmarkImages\\Cairo_Tower\\2.jpg"
                        },
                        new
                        {
                            Id = 20,
                            LandmarkId = 11,
                            Url = "\\landmarkImages\\National_Museum_of Egyptian_Civilization\\1.jpg"
                        },
                        new
                        {
                            Id = 21,
                            LandmarkId = 12,
                            Url = "\\landmarkImages\\Colossi_of_Memnon\\1.jpg"
                        },
                        new
                        {
                            Id = 22,
                            LandmarkId = 13,
                            Url = "\\landmarkImages\\Coptic_Museum\\1.jpg"
                        },
                        new
                        {
                            Id = 23,
                            LandmarkId = 14,
                            Url = "\\landmarkImages\\Deir_el-Medina\\1.jpeg"
                        },
                        new
                        {
                            Id = 24,
                            LandmarkId = 15,
                            Url = "\\landmarkImages\\Denderah\\1.jpg"
                        },
                        new
                        {
                            Id = 25,
                            LandmarkId = 16,
                            Url = "\\landmarkImages\\Edfu_Temple\\1.jpg"
                        },
                        new
                        {
                            Id = 26,
                            LandmarkId = 17,
                            Url = "\\landmarkImages\\Egyptian_Museum\\1.jpg"
                        },
                        new
                        {
                            Id = 28,
                            LandmarkId = 18,
                            Url = "\\landmarkImages\\Al-Azhar_Mosque\\1.jpg"
                        },
                        new
                        {
                            Id = 29,
                            LandmarkId = 19,
                            Url = "\\landmarkImages\\Temple_of_Gerf_Hussein\\1.jpg"
                        },
                        new
                        {
                            Id = 30,
                            LandmarkId = 20,
                            Url = "\\landmarkImages\\Al-Hussein_Mosque\\2.jpg"
                        });
                });

            modelBuilder.Entity("Explore_Egypt.Models.SearchHistory", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("LandmarkID")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("Date")
                        .HasColumnType("time");

                    b.HasKey("UserId", "LandmarkID");

                    b.HasIndex("LandmarkID");

                    b.ToTable("SearchHistory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "security");
                });

            modelBuilder.Entity("Explore_Egypt.Models.Favour", b =>
                {
                    b.HasOne("Explore_Egypt.Models.Landmark", "Landmark")
                        .WithMany("Favourites")
                        .HasForeignKey("LandmarkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Explore_Egypt.Models.ApplicationUser", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Landmark");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Explore_Egypt.Models.LandmarkImage", b =>
                {
                    b.HasOne("Explore_Egypt.Models.Landmark", "Landmark")
                        .WithMany("Images")
                        .HasForeignKey("LandmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Landmark");
                });

            modelBuilder.Entity("Explore_Egypt.Models.SearchHistory", b =>
                {
                    b.HasOne("Explore_Egypt.Models.Landmark", "Landmark")
                        .WithMany("SearchHistories")
                        .HasForeignKey("LandmarkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Explore_Egypt.Models.ApplicationUser", "User")
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Landmark");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Explore_Egypt.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Explore_Egypt.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Explore_Egypt.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Explore_Egypt.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Explore_Egypt.Models.ApplicationUser", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("SearchHistories");
                });

            modelBuilder.Entity("Explore_Egypt.Models.Landmark", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("Images");

                    b.Navigation("SearchHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
